#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH

destination_dir=$1

if [ -z "$destination_dir" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

mkdir -p $destination_dir

echo '{}' >&3

exit 0
